import "./styles/globals.scss";
import { Georama } from "next/font/google";
import Header from "./components/Header/Header";
import Socials from "./components/Socials/Socials";

const georama = Georama({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={georama.className}>
        <Header />
        {children}
        <Socials />
      </body>
    </html>
  );
}
